### ISSUE TITLE
Problems when start training:ModuleNotFoundError: No module named 'mel2wav'

### ISSUE THREAD

**Issue by HGZDG** [descriptinc/melgan-neurips#12]
when i type in python3 scripts/train.py --save_path logs/baseline/ --data_path wavs/
it shows that 
Traceback (most recent call last):
  File "scripts/train.py", line 2, in <module>
    from mel2wav.dataset import AudioDataset
ModuleNotFoundError: No module named 'mel2wav'
How to solve this problem?

**Comment by vashishtmarhwal** [comment]
Were you able to solve this issue?

**Comment by ghost** [comment]
@HGZDG

**Comment by tdeboissiere** [comment]
Try: ` PYTHONPATH=$PWD:$PYTHONPATH python XXX`

**Comment by Mariaa98** [comment]
i have same issue what should i do

**Comment by MckinstryJ** [comment]
I ran train.py in PyCharm and it works with this as its configuration parameter:

--save_path logs/baseline --data_path <location to wav folder that has train / test txt file>

No need for PYTHONPATH in my case.

Granted... I ran out of memory on my 2 GB cap GPU (on my laptop) using the LJSpeech wav files. I'll try to switch to a 8 GB cap GPU.
