### ISSUE TITLE
Tacotron2 + melgan = strange noise

### ISSUE THREAD

**Issue by vcjob** [descriptinc/melgan-neurips#14]
Hello everyone!

I tried that awsome work with tacotron2 TTS, but unfortunately can't make it work.
I use pretrained multi-speaker model from the repo. When I generate the audio, the output is the noise. I don't know why. One more thing to mention - TTS model is not for English. Well, it will probably anyway not be good at other languages than English, but should work I guess. 
I use 16k sample rate, 1 channel.
Please, take a look at the file attached!
[177.zip](https://github.com/descriptinc/melgan-neurips/files/3941652/177.zip)

Do you have any ideas on how to make it work? 
I save the file like this:

    _audio = (audio.cpu().numpy().reshape((-1))*2**15).astype(np.int16) #
    scipy.io.wavfile.write(file_path, sampling_rate, audio)_

**Comment by vcjob** [comment]
I see, it basically can't be combined with Tacotron 2. I gotta use another TTS.

**Comment by casper-hansen** [comment]
@vcjob did you get something working?
