### ISSUE TITLE
What is <root_data_folder>？

### ISSUE THREAD

**Issue by nikawool** [descriptinc/melgan-neurips#15]
In the training examples, the command "python scripts/train.py --save_path logs/baseline --path <root_data_folder>", which folder is <root_data_folder>?

**Comment by tdeboissiere** [comment]
This is the folder containing `train_files.txt`, `test_files.txt` and `wavs`.

Note that the README has to be updated (it's `--data_path` , not `--path`)

**Comment by nikawool** [comment]
> This is the folder containing `train_files.txt`, `test_files.txt` and `wavs`.
> 
> Note that the README has to be updated (it's `--data_path` , not `--path`)

thank you! 
I've been training for 9 hours and it hasn't stopped. How long did you train the sample? Do you train with CPU or GPU?

**Comment by ghost** [comment]
@tdeboissiere Did you get good results from melgan?
then upload some samples

**Comment by tdeboissiere** [comment]
@nikawool Depending on your dataset and amount of compute, training can take as long as 2 weeks.

@deepseek Samples are uploaded here: https://melgan-neurips.github.io/
