### ISSUE TITLE
Swapping Mel spectrogram with CQT spectrogram

### ISSUE THREAD

**Issue by mcallistertyler** [descriptinc/melgan-neurips#16]
There has been some research indicating that [CQT spectrogram can be better suited to music data](https://arxiv.org/abs/1811.09620). Do you think it would be possible to change the Mel spectrogram generation to CQT without making many changes to the underlying model? This is something I am interested in attempting.

**Comment by tdeboissiere** [comment]
@mcallistertyler95 The only thing you would need to change for the model to actually run is the input size (i.e our mel spectrogram has 80 channels, you may have a different number of channels for CQT).

However, we did not try training with CQT spectrogram so we cannot guarantee that it will actually converge to good results.

**Comment by mcallistertyler** [comment]
Thanks! I'm not sure if I should open a new issue for this seeing as this one is still open, but could I ask the purpose of the lines 55 - 56 in `modules.py`?

`p = (self.n_fft - self.hop_length) // 2`
`audio = F.pad(audio, (p, p), "reflect").squeeze(1)`
