### ISSUE TITLE
Not able to start training. Give mel2wav not found error

### ISSUE THREAD

**Issue by vashishtmarhwal** [descriptinc/melgan-neurips#18]
Traceback (most recent call last):
  File "scripts/train.py", line 1, in <module>
    from mel2wav.dataset import AudioDataset
ModuleNotFoundError: No module named 'mel2wav'

**Comment by tdeboissiere** [comment]
Try:  `PYTHONPATH=$PWD:$PYTHONPATH python`

**Comment by samiyaafzalminhas** [comment]
I am trying to run the train.py file on colab using !python path and it gives me this error. What should I possible do ? The structure of that folder is 
[
![github path](https://user-images.githubusercontent.com/81859487/234248868-32c7c843-ea9d-498d-a8ed-ca5e9751d141.png)
](url)

and this is how i am trying to run it on colab.
![pathss](https://user-images.githubusercontent.com/81859487/234248969-0225758f-19f3-45b2-af79-4ecd245d6b13.png)


any help is highly appreciated
