### ISSUE TITLE
Sample training dataset

### ISSUE THREAD

**Issue by ghost** [descriptinc/melgan-neurips#2]
@ritheshkumar95 
A sample dataset to test if training works.

**Comment by binarythinktank** [comment]
i would be interested in this too, especially to understand how much training wavs/minutes of speaking are actually needed for an accurate result

**Comment by ritheshkumar95** [comment]
This is a popular example dataset (also used in this paper) - https://keithito.com/LJ-Speech-Dataset.

You could download this and extract it, and follow the instructions mentioned

**Comment by binarythinktank** [comment]
perfect, thank you @ritheshkumar95
