### ISSUE TITLE
about models/*.pt

### ISSUE THREAD

**Issue by MorganCZY** [descriptinc/melgan-neurips#3]
could you please explain what kind of datasets are used to get models "linda_johnson.pt" and "multi_speaker.pt"?  Is "multi_speaker.pt" model corresponding to 
![multispeaker](https://user-images.githubusercontent.com/33675916/67753870-63d9a580-fa70-11e9-8267-e24ab98ea450.png) in the paper? And what's for "linda_johnson.pt" model?

**Comment by wezteoh** [comment]
`linda_johnson.pt` is trained using the open source dataset https://keithito.com/LJ-Speech-Dataset/

Yes, `multi_speaker.pt` is trained using our internal multispeaker dataset, and is expected to generalize across new speakers.

**Comment by MorganCZY** [comment]
@wezteoh I tested the multi_speaker.pt model to synthesize new speakers' sounds and it did well. Have your team explored how long at least the training dataset of each speaker should be and how many speakers at least are needed to achieve such an effect? btw, for your internal multispeaker, are they all English speakers?

**Comment by wezteoh** [comment]
all english speakers, and we used about 10 hours each.

**Comment by MorganCZY** [comment]
Thx! Besides when i run this repo with LJSpeech, i find the training is too slow on a 2080Ti gpu, far from the reference time  in the demo webpage.(shown in the picture)
![question](https://user-images.githubusercontent.com/33675916/67916451-af0aca00-fbd0-11e9-9bf5-abea75837de6.png)
I stripped out the mel calculating module and fed the pre-processed mel directly into training process by dataloader, but it didn't accelerate the training. Could you give me some speeding-up advice?

**Comment by MorganCZY** [comment]
I rewrote AudioDataset to directly feed processed audio data rather than processing wavs into audio data. The training speed is now close to the given one.

**Comment by ghost** [comment]
@MorganCZY so create a pull request

**Comment by casper-hansen** [comment]
@MorganCZY can you share your code?
