### ISSUE TITLE
No module named 'mel2wav'

### ISSUE THREAD

**Issue by allenhung1025** [descriptinc/melgan-neurips#33]
![2020-09-09 15-29-36 的螢幕擷圖](https://user-images.githubusercontent.com/22190213/92568192-64a6af00-f2b1-11ea-8b2a-daf4ab317dc1.png)
Hi all,
I have run the code successfully before with the same code. However, I got stuck here with out knowing what happened here. Does anyone know how to solve this problem?

**Comment by kynnemall** [comment]
I'm having the same issue. How did you fix the issue?

**Comment by ernestchu** [comment]
@kynnemall add these to the `train.py`
```py
import sys, os
sys.path.append(os.path.dirname(sys.path[0]))
```
