### ISSUE TITLE
How can I start training?

### ISSUE THREAD

**Issue by deep-darkfantasy** [descriptinc/melgan-neurips#8]
Traceback (most recent call last):
  File "scripts/train.py", line 231, in <module>
    main()
  File "scripts/train.py", line 90, in main
    Path(args.data_path) / "train_files.txt", args.seq_len, sampling_rate=16000,
  File "/home/yxd/python3.6/python3/lib/python3.6/pathlib.py", line 979, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/yxd/python3.6/python3/lib/python3.6/pathlib.py", line 654, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/yxd/python3.6/python3/lib/python3.6/pathlib.py", line 638, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
I seem to have encountered some problems while running.How should I handle this?

**Comment by jeewenjie** [comment]
Did you run set_env.sh?

**Comment by jeewenjie** [comment]
Did you run set_env.sh?

**Comment by jeewenjie** [comment]
Did you run set_env.sh?

**Comment by deep-darkfantasy** [comment]
> 您是否运行过set_env.sh？
Thank you, I ran before the program ran. 
source set_env.sh 0 
python3 scripts/train.py --save_path logs/baseline/
tensorflow-gpu 1.14
cuda10.1

**Comment by jeewenjie** [comment]
You seem to have left out the data folder argument.

>python scripts/train.py --save_path logs/baseline **--load_path <root_data_folder>**

**Comment by deep-darkfantasy** [comment]
> 您似乎遗漏了数据文件夹参数。
> 
> > python scripts / train.py --save_path日志/基线**--load_path <root_data_folder>**

thank you，This solved my problem，python3 scripts/train.py --save_path logs/baseline/ --data_path wavs/

**Comment by Mariaa98** [comment]
!python scripts/train.py --save_path logs/baseline --path /content/drive/My Drive/Melgan/melgan-neurips (this is command
and gives me an error 
Traceback (most recent call last):
  File "scripts/train.py", line 1, in <module>
    from mel2wav.dataset import AudioDataset
ModuleNotFoundError: No module named 'mel2wav'

the directory is right 
what should i do

**Comment by jeewenjie** [comment]
_Probably_ your PYTHONPATH is not set. Just export it.

export PYTHONPATH=/your/working/directory

**Comment by Mariaa98** [comment]
export PYTHONPATH= /content/drive/My Drive/Melgan/melgan-neurips 
it gives me invalid syntax
and i tried 
! echo $PYTHONPATH

import os
os.environ['PYTHONPATH'] += "/content/drive/My Drive/Melgan/melgan-neurips"

! echo $PYTHONPATH
and gives me same error
