### ISSUE TITLE
Missing sentences in paper v2.

### ISSUE THREAD

**Issue by jeewenjie** [descriptinc/melgan-neurips#9]
I believe there is some missing words in Section 3.2 of your paper.

>The results indicate that MelGAN is comparable to some of the best performing models to date
as a vocoder component of TTS pipeline. To the best of our ability we also created a TTS model
with Text2mel + WaveNet vocoder to add to our comparison. We use the pretrained WaveNet
vocoder model provided by Yamamoto (2019) and train the Text2mel model with the required data
preprocessing performed. However the model only obtained an MOS score of 3.40 ± 0.04. We
suspect that

I wish to clarify what the remaining of the section is.

Thank you.

**Comment by ritheshkumar95** [comment]
"For all our end-to-end text to speech experiments, we only trained the neural vocoder on ground-truth spectrograms and directly use it on generated spectrograms. However, we suspect that the poor results of our Text2Mel + WaveNet experiment could be the result of not finetuning the WaveNet vocoder on generated spectrograms (as performed in tacotron2)"

This is what I had wanted to write but it looks like we literally got lost in thought and missed this in the paper. Thanks for pointing it out, i will update this in the camera ready of NeurIPS and arxiv.
